[workspace]
members = ["libs/sql-parser", "libs/sql-analyzer", "test"]

[package]
name = "safe-sql"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
syn = "2"
sql-parser = { path = "libs/sql-parser" }
sql-analyzer = { path = "libs/sql-analyzer" }
